/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.rejestracja_i_logowanie;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Dzemor
 */
public class Rejestracja_i_logowanie extends javax.swing.JFrame {

    /**
     * Creates new form Rejestracja_i_logowanie
     */
    public Rejestracja_i_logowanie() {
        initComponents();
        addKeyListenerToUsername();
        addKeyListnerToPassword();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ms_jTabbedPaneMain = new javax.swing.JTabbedPane();
        ms_jPanelRegister = new javax.swing.JPanel();
        ms_jLabelRegister = new javax.swing.JLabel();
        ms_jLabelUsername = new javax.swing.JLabel();
        ms_jTextFieldUsername = new javax.swing.JTextField();
        ms_jLabeEmaill = new javax.swing.JLabel();
        ms_jTextFieldEmail = new javax.swing.JTextField();
        ms_jLabelConfirmPassword = new javax.swing.JLabel();
        ms_jPasswordFieldPassword = new javax.swing.JPasswordField();
        ms_jLabelPassword = new javax.swing.JLabel();
        ms_jPasswordFieldConfirmPassword = new javax.swing.JPasswordField();
        ms_jButtonRegister = new javax.swing.JButton();
        ms_jPanelLogin = new javax.swing.JPanel();
        ms_jLabelLogin = new javax.swing.JLabel();
        ms_jLabelLoginEmail = new javax.swing.JLabel();
        ms_jTextFieldLoginEmail = new javax.swing.JTextField();
        ms_jLabelLoginPassword = new javax.swing.JLabel();
        ms_jPasswordFieldLoginPassword = new javax.swing.JPasswordField();
        ms_jButtonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rejestracja i logowanie");
        setResizable(false);

        ms_jPanelRegister.setBackground(new java.awt.Color(255, 255, 255));

        ms_jLabelRegister.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ms_jLabelRegister.setText("Rejestracja");

        ms_jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelUsername.setText("Username");

        ms_jLabeEmaill.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabeEmaill.setText("Email");

        ms_jLabelConfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelConfirmPassword.setText("Confirm password");

        ms_jLabelPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelPassword.setText("Password");

        ms_jButtonRegister.setText("Rejetracja");
        ms_jButtonRegister.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        ms_jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonRegisterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ms_jPanelRegisterLayout = new javax.swing.GroupLayout(ms_jPanelRegister);
        ms_jPanelRegister.setLayout(ms_jPanelRegisterLayout);
        ms_jPanelRegisterLayout.setHorizontalGroup(
            ms_jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ms_jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ms_jTextFieldUsername)
                    .addComponent(ms_jTextFieldEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ms_jPasswordFieldPassword)
                    .addComponent(ms_jPasswordFieldConfirmPassword)
                    .addGroup(ms_jPanelRegisterLayout.createSequentialGroup()
                        .addGroup(ms_jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ms_jLabelRegister)
                            .addComponent(ms_jLabelUsername)
                            .addComponent(ms_jLabeEmaill)
                            .addComponent(ms_jLabelConfirmPassword)
                            .addComponent(ms_jLabelPassword)
                            .addComponent(ms_jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 356, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ms_jPanelRegisterLayout.setVerticalGroup(
            ms_jPanelRegisterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelRegisterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_jLabelRegister)
                .addGap(18, 18, 18)
                .addComponent(ms_jLabelUsername)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jTextFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ms_jLabeEmaill)
                .addGap(18, 18, 18)
                .addComponent(ms_jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(ms_jLabelPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ms_jPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ms_jLabelConfirmPassword)
                .addGap(18, 18, 18)
                .addComponent(ms_jPasswordFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_jButtonRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
        );

        ms_jTabbedPaneMain.addTab("Rejestracja", ms_jPanelRegister);

        ms_jPanelLogin.setBackground(new java.awt.Color(255, 255, 255));

        ms_jLabelLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        ms_jLabelLogin.setText("Logowanie");

        ms_jLabelLoginEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelLoginEmail.setText("Email");

        ms_jTextFieldLoginEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jTextFieldLoginEmailActionPerformed(evt);
            }
        });

        ms_jLabelLoginPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ms_jLabelLoginPassword.setText("Password");

        ms_jButtonLogin.setText("Login");
        ms_jButtonLogin.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        ms_jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ms_jButtonLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ms_jPanelLoginLayout = new javax.swing.GroupLayout(ms_jPanelLogin);
        ms_jPanelLogin.setLayout(ms_jPanelLoginLayout);
        ms_jPanelLoginLayout.setHorizontalGroup(
            ms_jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ms_jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ms_jTextFieldLoginEmail)
                    .addComponent(ms_jPasswordFieldLoginPassword)
                    .addGroup(ms_jPanelLoginLayout.createSequentialGroup()
                        .addGroup(ms_jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ms_jLabelLogin)
                            .addComponent(ms_jLabelLoginEmail)
                            .addComponent(ms_jLabelLoginPassword)
                            .addComponent(ms_jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 363, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ms_jPanelLoginLayout.setVerticalGroup(
            ms_jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ms_jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ms_jLabelLogin)
                .addGap(18, 18, 18)
                .addComponent(ms_jLabelLoginEmail)
                .addGap(18, 18, 18)
                .addComponent(ms_jTextFieldLoginEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ms_jLabelLoginPassword)
                .addGap(18, 18, 18)
                .addComponent(ms_jPasswordFieldLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ms_jButtonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                .addGap(171, 171, 171))
        );

        ms_jTabbedPaneMain.addTab("Logowanie", ms_jPanelLogin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jTabbedPaneMain)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ms_jTabbedPaneMain)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addKeyListenerToUsername(){
        ms_jTextFieldUsername.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                String temp = ms_jTextFieldUsername.getText();
                if(ch == KeyEvent.VK_BACK_SPACE || ch >= 65 && ch <= 90 || ch >= 97 && ch <= 122){
                    ms_jTextFieldUsername.setEditable(true);
                    if(temp.length() <= 20 || ch == KeyEvent.VK_BACK_SPACE){
                        ms_jTextFieldUsername.setEditable(true);
                    }else{
                        ms_jTextFieldUsername.setEditable(false);
                    }
                }else{
                    ms_jTextFieldUsername.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
    private void addKeyListnerToPassword(){
        ms_jPasswordFieldPassword.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch == KeyEvent.VK_BACK_SPACE || ch >= 65 && ch <= 90 || ch >= 97 && ch <= 122 || ch >= 48 && ch <= 57){
                    ms_jPasswordFieldPassword.setEditable(true);
                }else{
                    ms_jPasswordFieldPassword.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
        ms_jPasswordFieldConfirmPassword.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch == KeyEvent.VK_BACK_SPACE || ch >= 65 && ch <= 90 || ch >= 97 && ch <= 122 || ch >= 48 && ch <= 57){
                    ms_jPasswordFieldConfirmPassword.setEditable(true);
                }else{
                    ms_jPasswordFieldConfirmPassword.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
        ms_jPasswordFieldLoginPassword.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch == KeyEvent.VK_BACK_SPACE || ch >= 65 && ch <= 90 || ch >= 97 && ch <= 122 || ch >= 48 && ch <= 57){
                    ms_jPasswordFieldLoginPassword.setEditable(true);
                }else{
                    ms_jPasswordFieldLoginPassword.setEditable(false);
                }
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
    }
    private void ms_jTextFieldLoginEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jTextFieldLoginEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ms_jTextFieldLoginEmailActionPerformed

    private void ms_jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonRegisterActionPerformed
        FileUtils stf = new FileUtils();
        boolean tempUsername = false;
        int user = ms_jTextFieldUsername.getText().length();
        if(user >= 2){
           tempUsername = true;
        }else{
           tempUsername = false;
        }
        boolean tempPassword = false;
        int pass1 = ms_jPasswordFieldPassword.getPassword().length;
        if(pass1>= 4){
           tempPassword = true;
        }else{
           tempPassword = false;
        }
        boolean tempPassword1 = false;
        int pass2 = ms_jPasswordFieldConfirmPassword.getPassword().length;
        if(pass2>= 4){
           tempPassword1 = true;
        }else{
           tempPassword1 = false;
        }
        boolean passwordEq = false;
        String temp = ms_jTextFieldEmail.getText();
        String [] splitted = temp.split("@");
        boolean emai = true;
      String email = ms_jTextFieldEmail.getText();
        if(email.contains("@") && email.contains(".")){
            if(email.charAt(0)=='@'){
               emai = false;
            }else{
                String host[] = email.split("@");
                if(host[1].charAt(0)=='.'){
                    emai = false;
                }
                String dot = host[1];
                String dot2[] = dot.split("\\.");
                if(dot2[1].isEmpty()==true){
                    emai = false;
                }
            }
        }else{
            emai = false;
        }
        if(Arrays.equals(ms_jPasswordFieldPassword.getPassword(), ms_jPasswordFieldConfirmPassword.getPassword())){
            passwordEq = true;
        }else{
            passwordEq = false;
        }
        String usersString = stf.readFromFile();
        String[] lines = usersString.split("\\r?\\n");
        if(tempUsername== true && tempPassword == true && tempPassword1 == true && passwordEq == true && emai == true){
            JOptionPane.showMessageDialog(null, "Pomyślnie zarejstrowano: "+ms_jTextFieldUsername.getText());
            String text = ms_jTextFieldUsername.getText()+":"+ms_jTextFieldEmail.getText()+":"+String.valueOf(ms_jPasswordFieldPassword.getPassword());
            stf.saveToFile(text);
        }else{
            System.out.println("Cos tu nie gra");
        }
        if(tempUsername == false)JOptionPane.showMessageDialog(null, "Nieprawidłowa nazwa użytkownika", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
        if(emai == false)JOptionPane.showMessageDialog(null, "Nieprawidłowy email", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
        if(passwordEq == false)JOptionPane.showMessageDialog(null, "Hasła nie są takie same", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
        if(tempPassword == false)JOptionPane.showMessageDialog(null, "Nieprawidłowe hasło", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
        if(tempPassword1 == false)JOptionPane.showMessageDialog(null, "Nieprawidłowe hasło", "BŁĄD!", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_ms_jButtonRegisterActionPerformed
    private void ms_jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ms_jButtonLoginActionPerformed
        String emai = ms_jTextFieldLoginEmail.getText();
        String pass = String.valueOf(ms_jPasswordFieldLoginPassword.getPassword());
        FileUtils stf = new FileUtils();
        String usersString = stf.readFromFile();
        String[] lines = usersString.split("\\r?\\n");
        for (String user : lines) {
            String userSplitted[] = user.split(":");
            if(emai.equals(userSplitted[1]) && pass.equals(userSplitted[2])){
                JOptionPane.showMessageDialog(null, "Witaj: "+userSplitted[0]);
                return;
            }
        }
    }//GEN-LAST:event_ms_jButtonLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rejestracja_i_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rejestracja_i_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rejestracja_i_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rejestracja_i_logowanie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rejestracja_i_logowanie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ms_jButtonLogin;
    private javax.swing.JButton ms_jButtonRegister;
    private javax.swing.JLabel ms_jLabeEmaill;
    private javax.swing.JLabel ms_jLabelConfirmPassword;
    private javax.swing.JLabel ms_jLabelLogin;
    private javax.swing.JLabel ms_jLabelLoginEmail;
    private javax.swing.JLabel ms_jLabelLoginPassword;
    private javax.swing.JLabel ms_jLabelPassword;
    private javax.swing.JLabel ms_jLabelRegister;
    private javax.swing.JLabel ms_jLabelUsername;
    private javax.swing.JPanel ms_jPanelLogin;
    private javax.swing.JPanel ms_jPanelRegister;
    private javax.swing.JPasswordField ms_jPasswordFieldConfirmPassword;
    private javax.swing.JPasswordField ms_jPasswordFieldLoginPassword;
    private javax.swing.JPasswordField ms_jPasswordFieldPassword;
    private javax.swing.JTabbedPane ms_jTabbedPaneMain;
    private javax.swing.JTextField ms_jTextFieldEmail;
    private javax.swing.JTextField ms_jTextFieldLoginEmail;
    private javax.swing.JTextField ms_jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
